---
- name: Get vector src
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.25.1/vector-{{ vector_version_tar }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vector-{{ vector_version_tar }}.tar.gz"
  tags:
    - Get vector
- name: unarchive vector src
  ansible.builtin.unarchive:
    src: /tmp/vector-{{ vector_version_tar }}.tar.gz
    dest: /tmp/
    remote_src: true
- name: copy vector to bin
  become: true
  ansible.builtin.copy:
    src: /tmp/vector-x86_64-unknown-linux-gnu/bin/vector
    dest: /bin/vector
    remote_src: true
    mode: 0755
- name: Creates directory
  become: true
  file:
    path: /var/lib/vector/local_logs
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
- name: create vector dir
  become: true
  ansible.builtin.file:
    path: /etc/vector
    state: directory
    mode: 0644
- name: copy vector_cfg from local to remote_src
  ansible.builtin.template:
    src: vector.j2
    dest: /etc/vector/vector.toml
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  become: true
- name: install as a service and start
  become: true
  template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  notify: Restart vector service


  