---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.49.170
vector:
  hosts:
    vector-01:
      ansible_host: 62.84.126.45
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.89.109