---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: host_ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: false  
provisioner:
  name: ansible
verifier:
  name: ansible
