{
 "title": "My dash",
 "time": { "from": "2023-06-03T16:51:25.710Z", "to": "2023-06-03T17:22:16.610Z" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (sum by (instance) (irate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[5m])) / ignoring(instance) sum by (instance) (irate(node_cpu_seconds_total{job=\"nodeexporter\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}"
    }
   ]
  }
 ]
}