---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.0.138
vector:
  hosts:
    vector-01:
      ansible_host: 84.201.132.241
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 84.201.158.46